mirrors:
  3.2: stable
  3.3: unstable
  nightly: testing
  rc: testing

templates:
  deb-community: |
    Origin: mongodb
    Label: mongodb
    Suite: {{ . OSname }}
    Codename: {{ . CodeName }}/mongodb-org
    Architectures: amd64
    Components: {{ . Component }}
    Description: MongoDB packages
  deb-enterprise: |
    Origin: mongodb
    Label: mongodb
    Suite: {{ .OSname }}
    Codename: {{ . CodeName }}/mongodb-enterprise
    Architectures: amd64 ppc64el s390x
    Components: {{ . Component }}
    Description: MongoDB packages
  index-page: |
    <!DOCTYPE html>
    <html>
     <head>
       <title>{{ . TITLE }}</title>
     </head>

     <body>
       <table>
        <tr><td>
          <h1>{{ . TITLE }}</h1>
        </td></tr>

        <tr><td>
          <hr>
        </td></tr>

        <tr><td>
          <a href='..'>Parent Directory</a>
        </td></tr>

        {{ for i in files }}
        <tr><td>
          <a href='{{ basename i }}'>{{ basename i }}</a>
        </td></tr>
        {{ endfor }}

        <tr><td>
          <hr>
        </td></tr>

        <tr><td>
          <address>{{ .RepoName }}</address>
        </td></tr>
      </table>
     </body>
    </html>


repos:

####################
#
# Community Repos:
#
####################

  - name: rhel5
    type: rpm
    edition: community
    bucket: repo.mongodb.org
    prefix: yum/redhat/5
    repos:
      - yum/redhat/5
      - yum/redhat/5Server

  - name: rhel6
    type: rpm
    edition: community
    bucket: repo.mongodb.org
    repos:
      - yum/redhat/6
      - yum/redhat/6Server

  - name: rhel7
    type: rpm
    edition: community
    bucket: repo.mongodb.org
    repos:
      - yum/redhat/7
      - yum/redhat/7Server

  - name: amazon-2013.03
    type: rpm
    edition: community
    bucket: repo.mongodb.org
    repos:
      - yum/amazon/2013.03/mongodb-org

  - name: suse11
    type: rpm
    edition: community
    bucket: repo.mongodb.org
    repos:
      - zypper/suse/11/mongodb-org

  - name: suse12
    type: rpm
    edition: community
    bucket: repo.mongodb.org
    repos:
      - zypper/suse/12/mongodb-org

  - name: debian8
    type: deb
    bucket: repo.mongodb.org
    edition: community
    repos:
      - apt/debian/dists/jessie/mongodb-org/main

  - name: debian7
    type: deb
    bucket: repo.mongodb.org
    edition: community
    repos:
      - apt/debian/dists/wheezy/mongodb-org/main

  - name: ubuntu1204
    type: deb
    edition: community
    bucket: repo.mongodb.org
    repos:
      - apt/ubuntu/dists/precise/mongodb-org/multiverse

  - name: ubuntu1404
    type: deb
    edition: community
    bucket: repo.mongodb.org
    repos:
      - apt/ubuntu/dists/trusty/mongodb-org/multiverse

  - name: ubuntu1604
    type: deb
    edition: community
    bucket: repo.mongodb.org
    repos:
      - apt/ubuntu/dists/xenial/mongodb-org/multiverse

####################
#
# Enterprise Repos:
#
####################

  - name: rhel5
    type: rpm
    edition: enterprise
    bucket: repo.mongodb.com
    repos:
      - yum/redhat/5
      - yum/redhat/5Server

  - name: rhel6
    type: rpm
    edition: enterprise
    bucket: repo.mongodb.com
    repos:
      - yum/redhat/6
      - yum/redhat/6Server

  - name: rhel7
    type: rpm
    edition: enterprise
    bucket: repo.mongodb.com
    repos:
      - yum/redhat/7
      - yum/redhat/7Server

  - name: amazon-2013.03
    type: rpm
    edition: enterprise
    bucket: repo.mongodb.com
    repos:
      - yum/amazon/2013.03/mongodb-enterprise

  - name: suse11
    type: rpm
    edition: enterprise
    bucket: repo.mongodb.com
    repos:
      - zypper/suse/11/mongodb-enterprise

  - name: suse12
    type: rpm
    edition: enterprise
    bucket: repo.mongodb.com
    repos:
      - zypper/suse/12/mongodb-enterprise

  - name: debian8
    type: deb
    edition: enterprise
    bucket: repo.mongodb.com
    repos:
      - apt/debian/dists/jessie/mongodb-enterprise/main

  - name: debian7
    type: deb
    edition: enterprise
    bucket: repo.mongodb.com
    repos:
      - apt/debian/dists/wheezy/mongodb-enterprise/main

  - name: ubuntu1204
    type: deb
    edition: enterprise
    bucket: repo.mongodb.com
    repos:
      - apt/ubuntu/dists/precise/mongodb-enterprise/multiverse

  - name: ubuntu1404
    type: deb
    edition: enterprise
    bucket: repo.mongodb.com
    repos:
      - apt/ubuntu/dists/trusty/mongodb-enterprise/multiverse

  - name: ubuntu1504
    type: deb
    edition: enterprise
    bucket: repo.mongodb.com
    repos:
      - apt/ubuntu/dists/vivid/mongodb-enterprise/multiverse

  - name: ubuntu1604
    type: deb
    edition: enterprise
    bucket: repo.mongodb.com
    repos:
      - apt/ubuntu/dists/xenial/mongodb-enterprise/multiverse
